### ISSUE TITLE
kitconcept.dsgvo breaks bin/instance adduser ..

### ISSUE THREAD

**Issue by zopyx** [kitconcept/kitconcept.dsgvo#2]
```
bin/instance1  adduser  XXX YYY

2018-07-11 08:16:44 WARNING plone.behavior Specifying 'for' in behavior 'Tiles' if no 'factory' is given has no effect and is superfluous.
Traceback (most recent call last):
  File "/home/staging/sandboxes/dynaexamples.com/parts/instance1/bin/interpreter", line 311, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/home/staging/.buildout/eggs/Products.PlonePAS-5.0.15-py2.7.egg/Products/PlonePAS/pas.py", line 99, in _doAddUser
    retval = _old_doAddUser(login, password, roles, domains)
  File "/home/staging/.buildout/eggs/Products.PluggableAuthService-1.11.0-py2.7.egg/Products/PluggableAuthService/PluggableAuthService.py", line 1025, in _doAddUser
    notify(PrincipalCreated(user))
  File "/home/staging/.buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/home/staging/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "/home/staging/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 139, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/staging/.buildout/eggs/zope.interface-4.4.3-py2.7-linux-x86_64.egg/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/staging/.buildout/eggs/zope.interface-4.4.3-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 607, in subscribers
    subscription(*objects)
  File "/home/staging/.buildout/eggs/Products.PluggableAuthService-1.11.0-py2.7.egg/Products/PluggableAuthService/events.py", line 83, in PASEventNotify
    adapters = subscribers((event.principal, event), None)
  File "/home/staging/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 139, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/staging/.buildout/eggs/zope.interface-4.4.3-py2.7-linux-x86_64.egg/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/staging/.buildout/eggs/zope.interface-4.4.3-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 607, in subscribers
    subscription(*objects)
  File "/home/staging/.buildout/eggs/kitconcept.dsgvo-1.0.0a13-py2.7.egg/kitconcept/dsgvo/events.py", line 26, in user_registered
    member = api.user.get(userid=user.getId())
  File "<decorator-gen-31>", line 2, in get
  File "/home/staging/.buildout/eggs/plone.api-1.8.3-py2.7.egg/plone/api/validation.py", line 112, in wrapped
    return function(*args, **kwargs)
  File "<decorator-gen-30>", line 2, in get
  File "/home/staging/.buildout/eggs/plone.api-1.8.3-py2.7.egg/plone/api/validation.py", line 149, in wrapped
    return function(*args, **kwargs)
  File "/home/staging/.buildout/eggs/plone.api-1.8.3-py2.7.egg/plone/api/user.py", line 122, in get
    portal_membership = portal.get_tool('portal_membership')
  File "<decorator-gen-2>", line 2, in get_tool
  File "/home/staging/.buildout/eggs/plone.api-1.8.3-py2.7.egg/plone/api/validation.py", line 77, in wrapped
    return function(*args, **kwargs)
  File "/home/staging/.buildout/eggs/plone.api-1.8.3-py2.7.egg/plone/api/portal.py", line 118, in get_tool
    return getToolByName(get(), name)
  File "/home/staging/.buildout/eggs/plone.api-1.8.3-py2.7.egg/plone/api/portal.py", line 82, in get
    'Unable to get the portal object. More info on '
plone.api.exc.CannotGetPortalError: Unable to get the portal object. More info on http://docs.plone.org/develop/plone.api/docs/api/exceptions.html#plone.api.exc.CannotGetPortalError
```

**Comment by tisto** [comment]
@zopyx try upgrading plone.behavior to the latest version. I will try to find time to look into this next week...

**Comment by zopyx** [comment]
plone.behavior 1.2.1 does not solve the problem
